runtime: nodejs8

instance_class: F2

env_variables:
  NODE_ENV: production
  APP_SECRET: "$APP_SECRET"


handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
