runtime: nodejs8

instance_class: F2

env_variables:
  APP_TITLE: 'shortlr.com | URL Shortener'
  APP_URL: https://shortlr.com/

includes:
  - gae_env.yaml

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
